; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rear_node
src_dir = src
data_dir = src/main_node/data

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = lib
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
upload_speed = 921600
monitor_speed = 115200

[env:main_node]
build_src_filter = +<main_node/*> -<rear_node/>
board_build.filesystem = littlefs
extra_scripts = pre:fix_mklittlefs.py
lib_deps =
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit NeoMatrix

[env:rear_node]
build_src_filter = +<rear_node/*> -<main_node/>
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit NeoPixel
